### ISSUE TITLE
Where do you sum in SOPD.cpp?

### ISSUE THREAD

**Issue by redsphinx** [NEU-Gou/kernel-metric-learning-reid#1]
In https://github.com/NEU-Gou/kernel-metric-learning-reid/blob/master/Assistant%20Code/KISSME/toolbox/helper/SOPD.cpp#L75 I don't see that there is an implementation for summing after you calculate the outer products of the differences? 

Also, if you sum, doesn't it reduce the values in formulas 12 and 13 to a singular value? so then in formula 16, how is M a matrix?

**Comment by NEU-Gou** [comment]
@redsphinx I'm not sure which paper you're referring. There is no formula 13 and 16 in our ECCV paper "Person Re-Identification using Kernel-based Metric Learning Methods". If you're referring the KISSME paper, it's better to directly contact with the authors.

**Comment by redsphinx** [comment]
sorry I mean the CVPR paper "Person Re-Identification using Kernel-based Metric Learning Methods" yes: https://files.icg.tugraz.at/seafhttp/files/aa427349-0840-4528-b49a-93e2db1808be/koestinger_cvpr_2012.pdf

**Comment by redsphinx** [comment]
Nevermind, there is a sum in there on line 75. The code is just really hard to read
